<?php

namespace App\Console\Commands;

use App\Blueprint\PayrollServiceInterface;
use App\Blueprint\Repositories\CompanyUserRolePermissionRepository;
use App\Blueprint\Repositories\PayrollRepository;
use App\Blueprint\Repositories\RequestApprovalStateRepository;
use App\Blueprint\Repositories\SalaryStatementAttendanceDetailRepository;
use App\Blueprint\Repositories\SalaryStatementAttendanceRepository;
use App\Blueprint\Repositories\SalaryStatementRepository;
use App\Blueprint\Repositories\UserFiledRequestRepository;
use App\Blueprint\Repositories\UserRepository;
use App\Concrete\AutoCreateAttendanceConcrete;
use App\Concrete\LeaveService;
use App\Concrete\SalaryStatementModuleServiceConcrete;
use App\Enums\Compensation;
use App\Enums\Formulable;
use App\Exceptions\UnexpectedException;
use App\Facades\Fractal;
use App\Jobs\MailEmployeePayslip;
use App\Models\Company;
use App\Models\Employee;
use App\Models\LeaveType;
use App\Models\Payroll;
use App\Models\SalaryStatement;
use App\Transformers\SalaryStatementAttendance\ListTransformer;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\App;

class Debug extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:debug';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {

    }

    private function notifyEmployeesPayslip(Payroll $payroll): void
    {
        foreach($payroll->salaryStatements as $salaryStatement){

            MailEmployeePayslip::dispatch($salaryStatement);
        }
    }

    private function salarySatementManualAddDetail()
    {
        $salaryStatement = SalaryStatement::query()->find(286);
        $payroll = $salaryStatement->payroll;
        $employee = $salaryStatement->employee;

        $salaryStatementModuleService = new SalaryStatementModuleServiceConcrete($payroll, $payroll->company);
        $salaryStatementModuleService->setEmployee($employee);
        $manualSalaryStatementItems = [
            '200.211.1' => [
                [
                    'component_name' => 'Manual deduction example',
                    'deduction' => 100
                ]
            ]
        ];

        $salaryStatementModuleService->processPipelineOfFormulasAndUpdateStatementSummary($salaryStatement, true, $manualSalaryStatementItems);
    }

    private function salaryStatementAttendance()
    {
        $filters = (object)[
            'employee_ids' => [3],
            'formulable_types' => [Formulable::EARNINGS->value],
            'earning_components' => [Compensation::BASIC_PAY->value, Compensation::LEAVE_PAY->value],
            'date_from' => '2025-01-01',
            'date_to' => '2025-12-31',
        ];

        $perDayStatements = app(SalaryStatementAttendanceRepository::class)->paginate($filters, ['salary_statement', 'payroll_components']);
        $perDayStatements = Fractal::collection($perDayStatements, ListTransformer::class);
        _debug($perDayStatements);
    }

    private function autogeneratedUsername()
    {
        for ($i = 0; $i < 1000; $i++) {
            app(UserRepository::class)->generateUsername([
                'family_name' => 'Doe',
                'given_name' => 'John'
            ]);
        }
    }

    /**
     * @throws UnexpectedException
     */
    private function autoCreateAttendance(): void
    {
        $validated = (object)[
            'replace_existing_attendance' => true,
            'company_id' => 4,
            'employee_ids' => [4],
            'assigned_employee_group_ids' => [],
            'date_from' => '2026-01-26',
            'date_to' => '2026-02-25',
        ];

        $autoCreateAttendance = new AutoCreateAttendanceConcrete();

        $errors = $autoCreateAttendance($validated);
    }

    private function salaryStatementAttendanceDetail()
    {
        $filters = (object)[
            'salary_statement_ids' => [112],
            'salary_statement_attendance_ids' => [1277, 1294],
        ];

        $attendanceDetails = App::make(SalaryStatementAttendanceDetailRepository::class)->list($filters);
    }

    private function salaryStatements()
    {
        $filters = (object)[
            'company_ids' => [4],
            'payroll_ids' => [12],
        ];

        $salaryStatements = App::make(SalaryStatementRepository::class)->paginate($filters);
    }

    private function payroll()
    {
        $payrollService = app(PayrollServiceInterface::class, [Company::find(1)]);
        $payroll = App::make(PayrollRepository::class)->model()::query()->find(244);

        //$payrollService->preProcessSalaryStatements($payroll);
    }

    private function userFiledRequest()
    {
        $filters = (object)[
            'account_id' => 2,
            'associated_companies' => [4],
            'user_ids' => [3],
            'statuses' => []
        ];

        app(UserFiledRequestRepository::class)->baseQueryBuilder($filters);
    }

    private function companyUserRolePermission()
    {
        $filters = (object)[
            'account_id' => 2,
            'associated_company' => 4,
            'user_id' => 3,
            'permission_keys' => [
                'approve-any-request',
                'view-leave-running-balance'
            ]
        ];

        app(CompanyUserRolePermissionRepository::class)->list($filters);
    }

    private function requestApprovalState()
    {
        $filters = (object)[
            'account_id' => 2,
            'associated_companies' => [4],
            'requestable_type' => 'attendance_adjustment_request',
            'requestable_ids' => [],
            'user_ids' => [14],
            'show_only_current_state' => false
        ];

        app(RequestApprovalStateRepository::class)->baseQueryBuilder($filters);
    }

    private function leaveRunningBalance($debug)
    {
        $employee = Employee::query()->find(4);
        $leaveType = LeaveType::query()->find(4);
        $leaveService = new LeaveService();

        match(true){
            $debug == 'running_balance_by_date' => $leaveService->getRunningBalanceByDate($employee, $leaveType, '2027-12-01'),
            $debug == 'balance_by_period_series' => $leaveService->getBalancePeriodSeries($employee, $leaveType, '2029-12-31'),
            $debug == 'debug_single_line_per_date_series' => $leaveService->debugBalanceMapBySingleLinePerDateSeries($employee, $leaveType, '2029-12-31')
        };
    }
}
