<?php

namespace App\Concrete\Tests;

use AllowDynamicProperties;
use App\Enums\Compensation;
use App\Enums\Formulable;
use App\Enums\SalaryStatementAttendanceDayType;
use App\Enums\SalaryStatementAttendanceStatus;
use App\Models\SalaryStatementAttendance;
use App\Traits\HasPayableDay;
use Carbon\CarbonInterface;

class AttendancePayItemsTests
{
    use HasPayableDay;

    public array $restDays = [];

    public function testCases(): array
    {
        return [
            [
                'test_case' => 'FULL PRESENT NON-REST WITH OT',
                'test' => false,
                'salary_statement_attendance' => SalaryStatementAttendance::hydrate([[
                    'date' => '2026-01-26',
                    'status' => SalaryStatementAttendanceStatus::FULL_PRESENT->value,
                    'day_type' => SalaryStatementAttendanceDayType::WORKING_DAY->value,
                ]])->first(),
                'assigned_earnings' => [
                    Compensation::BASIC_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::REGULAR_ALLOWANCE->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::OVERTIME->value => [
                        'hourly_rate' => null,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'global_earnings' => [
                ],
                'rest_days' => [CarbonInterface::SUNDAY, CarbonInterface::SATURDAY],
                'work_splits' => [
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 1.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.1,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 120.0,
                    ),
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.0,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 180,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.0,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 180.0,
                    ),
                ],
                'overtime_splits' => [
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.25,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 1.25,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.375,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 103.0,
                    ),
                    array (
                        'split_duration' => 150,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 1.25,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.375,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 0.0,
                    ),
                ],
                'expected' => [
                    'split_results' => [
                        'work_splits' => [
                            [
                                'date' => '2026-01-26 Night Working day non-rest day',
                                'ACTUAL_PRESENT' => 120.0,
                                'WORKED HOURS' => 2.0,
                                'REGULAR MULTIPLIER' => 1.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.1,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 200.0,
                                'NIGHT MULTIPLIER' => 0.10000000000000009,
                                '=>' => '=>',
                                'REGULAR_PAY' => 200.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 20.000000000000018,
                                'REST_DAY_PAY' => 0,
                            ],[
                                'date' => '2026-01-26 Regular Working day non-rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.0,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 600.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 600.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 0,
                            ],[
                                'date' => '2026-01-26 Regular Working day non-rest day',
                                'ACTUAL_PRESENT' => 180.0,
                                'WORKED HOURS' => 3.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.0,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 300.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 300.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 0,
                            ]
                        ],
                        'overtime_splits' => [
                            [
                                'date' => '2026-01-26 Regular Working day non-rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.25,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 600.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 750.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 0,
                            ],[
                                'date' => '2026-01-26 Night Working day non-rest day',
                                'ACTUAL_PRESENT' => 103.0,
                                'WORKED HOURS' => 1.7166666666666666,
                                'REGULAR MULTIPLIER' => 1.25,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.375,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 171.66666666666666,
                                'NIGHT MULTIPLIER' => 0.125,
                                '=>' => '=>',
                                'REGULAR_PAY' => 214.58333333333331,
                                'NIGHT_DIFFERENTIAL_PAY' => 21.458333333333332,
                                'REST_DAY_PAY' => 0,
                            ],[
                                'date' => '2026-01-26 Night Working day non-rest day',
                                'ACTUAL_PRESENT' => 0.0,
                                'WORKED HOURS' => 0.0,
                                'REGULAR MULTIPLIER' => 1.25,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.375,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 0.0,
                                'NIGHT MULTIPLIER' => 0.125,
                                '=>' => '=>',
                                'REGULAR_PAY' => 0.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0.0,
                                'REST_DAY_PAY' => 0,
                            ]
                        ],
                        'payable_non_attendance_work_splits' => []
                    ],
                    'pay_items' => [
                        array (
                            'formulable_type' => 100,
                            'component_type' => 100,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 20.000000000000018,
                            'rest_day_pay' => 0,
                            'total' => 1120.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 101,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 1100.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 110,
                            'work_hour_type' => 100,
                            'regular_pay' => 964.5833333333333,
                            'night_differential_pay' => 21.458333333333332,
                            'rest_day_pay' => 0,
                            'total' => 986.0416666666666,
                        ),
                    ],
                ]
            ],[
                'test_case' => 'FULL PRESENT NON-REST',
                'test' => false,
                'salary_statement_attendance' => SalaryStatementAttendance::hydrate([[
                    'date' => '2026-01-27',
                    'status' => SalaryStatementAttendanceStatus::FULL_PRESENT->value,
                    'day_type' => SalaryStatementAttendanceDayType::WORKING_DAY->value,
                ]])->first(),
                'assigned_earnings' => [
                    Compensation::BASIC_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::REGULAR_ALLOWANCE->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::OVERTIME->value => [
                        'hourly_rate' => NULL,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'global_earnings' => [
                ],
                'rest_days' => [CarbonInterface::SUNDAY, CarbonInterface::SATURDAY],
                'work_splits' => [
                    array (
                        'split_duration' => 120,
                        'work_hour_type' =>
                            \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 1.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.1,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 120.0,
                    ),
                    array (
                        'split_duration' => 360,
                        'work_hour_type' =>
                            \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.0,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 180,
                        'work_hour_type' =>
                            \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 1.0,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 180.0,
                    ),
                ],
                'overtime_splits' => [
                ],
                'expected' => [
                    'split_results' => [
                        'work_splits' => [
                            array (
                                'date' => '2026-01-27 Night Working day non-rest day',
                                'ACTUAL_PRESENT' => 120.0,
                                'WORKED HOURS' => 2.0,
                                'REGULAR MULTIPLIER' => 1.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.1,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 200.0,
                                'NIGHT MULTIPLIER' => 0.10000000000000009,
                                '=>' => '=>',
                                'REGULAR_PAY' => 200.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 20.000000000000018,
                                'REST_DAY_PAY' => 0,
                            ),
                            array (
                                'date' => '2026-01-27 Regular Working day non-rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.0,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 600.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 600.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 0,
                            ),
                            array (
                                'date' => '2026-01-27 Regular Working day non-rest day',
                                'ACTUAL_PRESENT' => 180.0,
                                'WORKED HOURS' => 3.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 1.0,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 300.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 300.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 0,
                            ),
                        ],
                        'overtime_splits' => [
                        ],
                        'payable_non_attendance_work_splits' => []
                    ],
                    'pay_items' => [
                        array (
                            'formulable_type' => 100,
                            'component_type' => 100,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 20.000000000000018,
                            'rest_day_pay' => 0,
                            'total' => 1120.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 101,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 1100.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 110,
                            'work_hour_type' => 100,
                            'regular_pay' => 0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 0,
                        ),
                    ],
                ]
            ],[
                'test_case' => 'FULL PRESENT REST DAY WITH OT',
                'test' => false,
                'salary_statement_attendance' => SalaryStatementAttendance::hydrate([[
                    'date' => '2026-01-31',
                    'status' => SalaryStatementAttendanceStatus::FULL_PRESENT->value,
                    'day_type' => SalaryStatementAttendanceDayType::WORKING_DAY->value,
                ]])->first(),
                'assigned_earnings' => [
                    Compensation::BASIC_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::REGULAR_ALLOWANCE->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::OVERTIME->value => [
                        'hourly_rate' => NULL,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'global_earnings' => [
                ],
                'rest_days' => [CarbonInterface::SUNDAY, CarbonInterface::SATURDAY],
                'work_splits' => [
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 1.3,
                        'non_rest_rate_multiplier' => 1.1,
                        'hourly_rate_multiplier' => 1.43,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 120.0,
                    ),
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 1.0,
                        'hourly_rate_multiplier' => 1.3,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 180,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 1.0,
                        'hourly_rate_multiplier' => 1.3,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 180.0,
                    ),
                ],
                'overtime_splits' => [
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 1.25,
                        'hourly_rate_multiplier' => 1.69,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 1.69,
                        'non_rest_rate_multiplier' => 1.375,
                        'hourly_rate_multiplier' => 1.859,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 103.0,
                    ),
                    array (
                        'split_duration' => 150,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 1.69,
                        'non_rest_rate_multiplier' => 1.375,
                        'hourly_rate_multiplier' => 1.859,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 0.0,
                    ),
                ],
                'expected' => [
                    'split_results' => [
                        'work_splits' => [
                            array (
                                'date' => '2026-01-31 Night Working day rest day',
                                'ACTUAL_PRESENT' => 120.0,
                                'WORKED HOURS' => 2.0,
                                'REGULAR MULTIPLIER' => 1.3,
                                'NON-RESTMULTIPLIER' => 1.1,
                                'HOURLYR_MULTIPLIER' => 1.43,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 200.0,
                                'NIGHT MULTIPLIER' => 0.1299999999999999,
                                'REST MULTIPLIER' => 0.30000000000000004,
                                '=>' => '=>',
                                'REGULAR_PAY' => 200.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 25.99999999999998,
                                'REST_DAY_PAY' => 60.00000000000001,
                            ),
                            array (
                                'date' => '2026-01-31 Regular Working day rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 1.0,
                                'HOURLYR_MULTIPLIER' => 1.3,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 600.0,
                                'REST MULTIPLIER' => 0.30000000000000004,
                                '=>' => '=>',
                                'REGULAR_PAY' => 600.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 180.00000000000003,
                            ),
                            array (
                                'date' => '2026-01-31 Regular Working day rest day',
                                'ACTUAL_PRESENT' => 180.0,
                                'WORKED HOURS' => 3.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 1.0,
                                'HOURLYR_MULTIPLIER' => 1.3,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 300.0,
                                'REST MULTIPLIER' => 0.30000000000000004,
                                '=>' => '=>',
                                'REGULAR_PAY' => 300.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 90.00000000000001,
                            ),
                        ],
                        'overtime_splits' => [
                            array (
                                'date' => '2026-01-31 Regular Working day rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 1.25,
                                'HOURLYR_MULTIPLIER' => 1.69,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 600.0,
                                'REST MULTIPLIER' => 0.43999999999999995,
                                '=>' => '=>',
                                'REGULAR_PAY' => 750.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 263.99999999999994,
                            ),
                            array (
                                'date' => '2026-01-31 Night Working day rest day',
                                'ACTUAL_PRESENT' => 103.0,
                                'WORKED HOURS' => 1.7166666666666666,
                                'REGULAR MULTIPLIER' => 1.69,
                                'NON-RESTMULTIPLIER' => 1.375,
                                'HOURLYR_MULTIPLIER' => 1.859,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 171.66666666666666,
                                'NIGHT MULTIPLIER' => 0.16900000000000004,
                                'REST MULTIPLIER' => 0.43999999999999995,
                                '=>' => '=>',
                                'REGULAR_PAY' => 214.58333333333331,
                                'NIGHT_DIFFERENTIAL_PAY' => 29.01166666666667,
                                'REST_DAY_PAY' => 75.53333333333332,
                            ),
                            array (
                                'date' => '2026-01-31 Night Working day rest day',
                                'ACTUAL_PRESENT' => 0.0,
                                'WORKED HOURS' => 0.0,
                                'REGULAR MULTIPLIER' => 1.69,
                                'NON-RESTMULTIPLIER' => 1.375,
                                'HOURLYR_MULTIPLIER' => 1.859,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 0.0,
                                'NIGHT MULTIPLIER' => 0.16900000000000004,
                                'REST MULTIPLIER' => 0.43999999999999995,
                                '=>' => '=>',
                                'REGULAR_PAY' => 0.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0.0,
                                'REST_DAY_PAY' => 0.0,
                            ),
                        ],
                        'payable_non_attendance_work_splits' => []
                    ],
                    'pay_items' => [
                        array (
                            'formulable_type' => 100,
                            'component_type' => 100,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 25.99999999999998,
                            'rest_day_pay' => 330.00000000000006,
                            'total' => 1456.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 101,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 1100.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 110,
                            'work_hour_type' => 100,
                            'regular_pay' => 964.5833333333333,
                            'night_differential_pay' => 29.01166666666667,
                            'rest_day_pay' => 339.53333333333325,
                            'total' => 1333.128333333333,
                        ),
                    ],
                ]
            ],[
                'test_case' => 'FULL PRESENT REST DAY LEGAL HOLIDAY WITH OT',
                'test' => false,
                'salary_statement_attendance' => SalaryStatementAttendance::hydrate([[
                    'date' => '2026-02-07',
                    'status' => SalaryStatementAttendanceStatus::FULL_PRESENT->value,
                    'day_type' => SalaryStatementAttendanceDayType::LEGAL_HOLIDAY->value,
                ]])->first(),
                'assigned_earnings' => [
                    Compensation::BASIC_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::REGULAR_ALLOWANCE->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::OVERTIME->value => [
                        'hourly_rate' => NULL,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'global_earnings' => [
                    Compensation::HOLIDAY_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'rest_days' => [CarbonInterface::SUNDAY, CarbonInterface::SATURDAY],
                'work_splits' => [
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 2.6,
                        'non_rest_rate_multiplier' => 2.2,
                        'hourly_rate_multiplier' => 2.86,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 120.0,
                    ),
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 2.0,
                        'hourly_rate_multiplier' => 2.6,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 180,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 2.0,
                        'hourly_rate_multiplier' => 2.6,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 180.0,
                    ),
                ],
                'overtime_splits' => [
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 2.6,
                        'hourly_rate_multiplier' => 3.38,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 3.38,
                        'non_rest_rate_multiplier' => 2.86,
                        'hourly_rate_multiplier' => 3.718,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 103.0,
                    ),
                    array (
                        'split_duration' => 150,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 3.38,
                        'non_rest_rate_multiplier' => 2.86,
                        'hourly_rate_multiplier' => 3.718,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 0.0,
                    ),
                ],
                'expected' => [
                    'split_results' => [
                        'work_splits' => [
                            array (
                                'date' => '2026-02-07 Night Legal holiday rest day',
                                'ACTUAL_PRESENT' => 120.0,
                                'WORKED HOURS' => 2.0,
                                'REGULAR MULTIPLIER' => 2.6,
                                'NON-RESTMULTIPLIER' => 2.2,
                                'HOURLYR_MULTIPLIER' => 2.86,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 200.0,
                                'NIGHT MULTIPLIER' => 0.2599999999999998,
                                'REST MULTIPLIER' => 0.6599999999999997,
                                'HOLIDAY MULTIPLIER' => 0.9400000000000004,
                                '=>' => '=>',
                                'REGULAR_PAY' => 200.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 51.99999999999996,
                                'REST_DAY_PAY' => 131.99999999999994,
                                'HOLIDAY_PAY' => 188.00000000000009,
                            ),
                            array (
                                'date' => '2026-02-07 Regular Legal holiday rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 2.0,
                                'HOURLYR_MULTIPLIER' => 2.6,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 600.0,
                                'REST MULTIPLIER' => 0.6000000000000001,
                                'HOLIDAY MULTIPLIER' => 1.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 600.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 360.00000000000006,
                                'HOLIDAY_PAY' => 600.0,
                            ),
                            array (
                                'date' => '2026-02-07 Regular Legal holiday rest day',
                                'ACTUAL_PRESENT' => 180.0,
                                'WORKED HOURS' => 3.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 2.0,
                                'HOURLYR_MULTIPLIER' => 2.6,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 300.0,
                                'REST MULTIPLIER' => 0.6000000000000001,
                                'HOLIDAY MULTIPLIER' => 1.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 300.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 180.00000000000003,
                                'HOLIDAY_PAY' => 300.0,
                            ),
                        ],
                        'overtime_splits' => [
                            array (
                                'date' => '2026-02-07 Regular Legal holiday rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 2.6,
                                'HOURLYR_MULTIPLIER' => 3.38,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 600.0,
                                'REST MULTIPLIER' => 0.7799999999999998,
                                'HOLIDAY MULTIPLIER' => 1.35,
                                '=>' => '=>',
                                'REGULAR_PAY' => 750.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 467.9999999999999,
                                'HOLIDAY_PAY' => 810.0,
                            ),
                            array (
                                'date' => '2026-02-07 Night Legal holiday rest day',
                                'ACTUAL_PRESENT' => 103.0,
                                'WORKED HOURS' => 1.7166666666666666,
                                'REGULAR MULTIPLIER' => 3.38,
                                'NON-RESTMULTIPLIER' => 2.86,
                                'HOURLYR_MULTIPLIER' => 3.718,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 171.66666666666666,
                                'NIGHT MULTIPLIER' => 0.3380000000000001,
                                'REST MULTIPLIER' => 0.8580000000000001,
                                'HOLIDAY MULTIPLIER' => 1.2719999999999998,
                                '=>' => '=>',
                                'REGULAR_PAY' => 214.58333333333331,
                                'NIGHT_DIFFERENTIAL_PAY' => 58.02333333333334,
                                'REST_DAY_PAY' => 147.29000000000002,
                                'HOLIDAY_PAY' => 218.35999999999996,
                            ),
                            array (
                                'date' => '2026-02-07 Night Legal holiday rest day',
                                'ACTUAL_PRESENT' => 0.0,
                                'WORKED HOURS' => 0.0,
                                'REGULAR MULTIPLIER' => 3.38,
                                'NON-RESTMULTIPLIER' => 2.86,
                                'HOURLYR_MULTIPLIER' => 3.718,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 0.0,
                                'NIGHT MULTIPLIER' => 0.3380000000000001,
                                'REST MULTIPLIER' => 0.8580000000000001,
                                'HOLIDAY MULTIPLIER' => 1.2719999999999998,
                                '=>' => '=>',
                                'REGULAR_PAY' => 0.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0.0,
                                'REST_DAY_PAY' => 0.0,
                                'HOLIDAY_PAY' => 0.0,
                            ),
                        ],
                        'payable_non_attendance_work_splits' => []
                    ],
                    'pay_items' => [
                        array (
                            'formulable_type' => 100,
                            'component_type' => 100,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 51.99999999999996,
                            'rest_day_pay' => 672.0,
                            'total' => 1824.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 101,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 1100.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 110,
                            'work_hour_type' => 100,
                            'regular_pay' => 964.5833333333333,
                            'night_differential_pay' => 58.02333333333334,
                            'rest_day_pay' => 615.29,
                            'total' => 1637.8966666666665,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 300,
                            'work_hour_type' => 100,
                            'regular_pay' => 2116.36,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 2116.36,
                        ),
                    ],
                ]
            ],[
                'test_case' => 'ABSENT LEGAL HOLIDAY',
                'test' => false,
                'salary_statement_attendance' => SalaryStatementAttendance::hydrate([[
                    'date' => '2026-02-09',
                    'status' => SalaryStatementAttendanceStatus::ABSENT->value,
                    'day_type' => SalaryStatementAttendanceDayType::LEGAL_HOLIDAY->value,
                ]])->first(),
                'assigned_earnings' => [
                    Compensation::BASIC_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::REGULAR_ALLOWANCE->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::OVERTIME->value => [
                        'hourly_rate' => NULL,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'global_earnings' => [
                    Compensation::HOLIDAY_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'rest_days' => [CarbonInterface::SUNDAY, CarbonInterface::SATURDAY],
                'work_splits' => [
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 2.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.2,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 0.0,
                    ),
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.0,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 0.0,
                    ),
                    array (
                        'split_duration' => 180,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.0,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 0.0,
                    ),
                ],
                'overtime_splits' => [
                ],
                'expected' => [
                    'split_results' => [
                        'work_splits' => [
                        ],
                        'overtime_splits' => [
                        ],
                        'payable_non_attendance_work_splits' => [
                            array (
                                'date' => '2026-02-09 Legal holiday non-rest day',
                                'work_hour_type' => 'Night',
                                'HOURLYR_MULTIPLIER' => 2.2,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'actual_present' => 0.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 200.0,
                            ),
                            array (
                                'date' => '2026-02-09 Legal holiday non-rest day',
                                'work_hour_type' => 'Regular',
                                'HOURLYR_MULTIPLIER' => 2.0,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'actual_present' => 0.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 600.0,
                            ),
                            array (
                                'date' => '2026-02-09 Legal holiday non-rest day',
                                'work_hour_type' => 'Regular',
                                'HOURLYR_MULTIPLIER' => 2.0,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'actual_present' => 0.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 300.0,
                            ),
                        ]
                    ],
                    'pay_items' => [
                        array (
                            'formulable_type' => 100,
                            'component_type' => 100,
                            'work_hour_type' => 100,
                            'regular_pay' => 0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 101,
                            'work_hour_type' => 100,
                            'regular_pay' => 0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 110,
                            'work_hour_type' => 100,
                            'regular_pay' => 0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 300,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 0,
                        ),
                    ],
                ]
            ],[
                'test_case' => 'FULL PRESENT REGULAR DAY LEGAL HOLIDAY',
                'test' => true,
                'salary_statement_attendance' => SalaryStatementAttendance::hydrate([[
                    'date' => '2026-02-10',
                    'status' => SalaryStatementAttendanceStatus::FULL_PRESENT->value,
                    'day_type' => SalaryStatementAttendanceDayType::LEGAL_HOLIDAY->value,
                ]])->first(),
                'assigned_earnings' => [
                    Compensation::BASIC_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::REGULAR_ALLOWANCE->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                    Compensation::OVERTIME->value => [
                        'hourly_rate' => NULL,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'global_earnings' => [
                    Compensation::HOLIDAY_PAY->value => [
                        'hourly_rate' => 100.0,
                        'work_hour_type' => 100,
                        'regular_pay' => 0,
                        'night_differential_pay' => 0,
                        'rest_day_pay' => 0,
                        'total' => 0,
                    ],
                ],
                'rest_days' => [CarbonInterface::SUNDAY, CarbonInterface::SATURDAY],
                'work_splits' => [
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 2.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.2,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 120.0,
                    ),
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.0,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 180,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.0,
                        'base_rate_multiplier' => 1.0,
                        'actual_present' => 180.0,
                    ),
                ],
                'overtime_splits' => [
                    array (
                        'split_duration' => 360,
                        'work_hour_type' => \App\Enums\WorkHourType::REGULAR,
                        'regular_rate_multiplier' => 0.0,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.6,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 360.0,
                    ),
                    array (
                        'split_duration' => 120,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 2.6,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.86,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 120.0,
                    ),
                    array (
                        'split_duration' => 150,
                        'work_hour_type' => \App\Enums\WorkHourType::NIGHT,
                        'regular_rate_multiplier' => 2.6,
                        'non_rest_rate_multiplier' => 0.0,
                        'hourly_rate_multiplier' => 2.86,
                        'base_rate_multiplier' => 1.25,
                        'actual_present' => 150.0,
                    ),
                ],
                'expected' => [
                    'split_results' => [
                        'work_splits' => [
                            array (
                                'date' => '2026-02-10 Night Legal holiday non-rest day',
                                'ACTUAL_PRESENT' => 120.0,
                                'WORKED HOURS' => 2.0,
                                'REGULAR MULTIPLIER' => 2.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 2.2,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 200.0,
                                'NIGHT MULTIPLIER' => 0.20000000000000018,
                                'HOLIDAY MULTIPLIER' => 1.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 200.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 40.000000000000036,
                                'REST_DAY_PAY' => 0,
                                'HOLIDAY_PAY' => 200.0,
                            ),
                            array (
                                'date' => '2026-02-10 Regular Legal holiday non-rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 2.0,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 600.0,
                                'HOLIDAY MULTIPLIER' => 1.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 600.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 0,
                                'HOLIDAY_PAY' => 600.0,
                            ),
                            array (
                                'date' => '2026-02-10 Regular Legal holiday non-rest day',
                                'ACTUAL_PRESENT' => 180.0,
                                'WORKED HOURS' => 3.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 2.0,
                                'BASE_RA_MULTIPLIER' => 1.0,
                                'BASIC' => 300.0,
                                'HOLIDAY MULTIPLIER' => 1.0,
                                '=>' => '=>',
                                'REGULAR_PAY' => 300.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 0,
                                'HOLIDAY_PAY' => 300.0,
                            ),
                        ],
                        'overtime_splits' => [
                            array (
                                'date' => '2026-02-10 Regular Legal holiday non-rest day',
                                'ACTUAL_PRESENT' => 360.0,
                                'WORKED HOURS' => 6.0,
                                'REGULAR MULTIPLIER' => 0.0,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 2.6,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 600.0,
                                'HOLIDAY MULTIPLIER' => 1.35,
                                '=>' => '=>',
                                'REGULAR_PAY' => 750.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 0,
                                'REST_DAY_PAY' => 0,
                                'HOLIDAY_PAY' => 810.0,
                            ),
                            array (
                                'date' => '2026-02-10 Night Legal holiday non-rest day',
                                'ACTUAL_PRESENT' => 120.0,
                                'WORKED HOURS' => 2.0,
                                'REGULAR MULTIPLIER' => 2.6,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 2.86,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 200.0,
                                'NIGHT MULTIPLIER' => 0.2599999999999998,
                                'HOLIDAY MULTIPLIER' => 1.35,
                                '=>' => '=>',
                                'REGULAR_PAY' => 250.0,
                                'NIGHT_DIFFERENTIAL_PAY' => 51.99999999999996,
                                'REST_DAY_PAY' => 0,
                                'HOLIDAY_PAY' => 270.0,
                            ),
                            array (
                                'date' => '2026-02-10 Night Legal holiday non-rest day',
                                'ACTUAL_PRESENT' => 150.0,
                                'WORKED HOURS' => 2.5,
                                'REGULAR MULTIPLIER' => 2.6,
                                'NON-RESTMULTIPLIER' => 0.0,
                                'HOURLYR_MULTIPLIER' => 2.86,
                                'BASE_RA_MULTIPLIER' => 1.25,
                                'BASIC' => 250.0,
                                'NIGHT MULTIPLIER' => 0.2599999999999998,
                                'HOLIDAY MULTIPLIER' => 1.35,
                                '=>' => '=>',
                                'REGULAR_PAY' => 312.5,
                                'NIGHT_DIFFERENTIAL_PAY' => 64.99999999999994,
                                'REST_DAY_PAY' => 0,
                                'HOLIDAY_PAY' => 337.5,
                            ),
                        ],
                        'payable_non_attendance_work_splits' => []
                    ],
                    'pay_items' => [
                        array (
                            'formulable_type' => 100,
                            'component_type' => 100,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 40.000000000000036,
                            'rest_day_pay' => 0,
                            'total' => 1140.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 101,
                            'work_hour_type' => 100,
                            'regular_pay' => 1100.0,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 1100.0,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 110,
                            'work_hour_type' => 100,
                            'regular_pay' => 1312.5,
                            'night_differential_pay' => 116.9999999999999,
                            'rest_day_pay' => 0,
                            'total' => 1429.5,
                        ),
                        array (
                            'formulable_type' => 100,
                            'component_type' => 300,
                            'work_hour_type' => 100,
                            'regular_pay' => 2517.5,
                            'night_differential_pay' => 0,
                            'rest_day_pay' => 0,
                            'total' => 2517.5,
                        ),
                    ],
                ]
            ],[
                'test_case' => 'TEST PAYLOAD',
                'test' => false,
                'salary_statement_attendance' => SalaryStatementAttendance::hydrate([[
                    'date' => '2026-01-27',
                    'status' => SalaryStatementAttendanceStatus::FULL_PRESENT->value,
                    'day_type' => SalaryStatementAttendanceDayType::WORKING_DAY->value,
                ]])->first(),
                'assigned_earnings' => [
                    Compensation::BASIC_PAY->value => [
                    ],
                    Compensation::REGULAR_ALLOWANCE->value => [
                    ],
                    Compensation::OVERTIME->value => [
                    ],
                ],
                'global_earnings' => [
                ],
                'rest_days' => [CarbonInterface::SUNDAY, CarbonInterface::SATURDAY],
                'work_splits' => [
                ],
                'overtime_splits' => [
                ],
                'expected' => [
                    'split_results' => [
                        'work_splits' => [
                        ],
                        'overtime_splits' => [
                        ],
                        'payable_non_attendance_work_splits' => []
                    ],
                    'pay_items' => [
                    ],
                ]
            ],
        ];
    }

    public function run($debug = false): string
    {
        _clear_debug();
        $passed = 0;
        $failed = 0;

        foreach ($this->testCases() as $testCase){

            if(!$testCase['test'])continue;

            $assignedEarningsPayload = $testCase['assigned_earnings'];
            $globalEarningsPayload = $testCase['global_earnings'];

            $this->workSplits = $testCase['work_splits'];
            $this->overtimeSplits = $testCase['overtime_splits'];
            $this->restDays = $testCase['rest_days'];

            $splitResults = $this->setSatementDateAmountOnEarningsPayload(
                $testCase['salary_statement_attendance'],
                $assignedEarningsPayload,
                $globalEarningsPayload,
                true,
                true
            );

            $assignedCompensationsPatchable = collect($assignedEarningsPayload)->map(fn($value, $key) => [
                'formulable_type' => Formulable::EARNINGS->value,
                'component_type' => $key,
                'work_hour_type' => $value['work_hour_type'],
                'regular_pay' => $value['regular_pay'],
                'night_differential_pay' => $value['night_differential_pay'],
                'rest_day_pay' => $value['rest_day_pay'],
                'total' => $value['total'],
            ])->values()->toArray();
            $globalCompensationsPatchable = collect($globalEarningsPayload)->map(fn($value, $key) => [
                'formulable_type' => Formulable::EARNINGS->value,
                'component_type' => $key,
                'work_hour_type' => $value['work_hour_type'],
                'regular_pay' => $value['regular_pay'],
                'night_differential_pay' => $value['night_differential_pay'],
                'rest_day_pay' => $value['rest_day_pay'],
                'total' => $value['total'],
            ])->values()->toArray();
            $attendancePayItemsPatchable = array_merge($assignedCompensationsPatchable, $globalCompensationsPatchable);

            if(
                $testCase['expected']['pay_items'] == $attendancePayItemsPatchable &&
                $testCase['expected']['split_results'] == $splitResults
            ){
                $passed++;
            } else {
                $failed++;
            }
        }

        return sprintf('%d/%d', $passed, $passed + $failed);
    }
}
