<?php

namespace App\Concrete\Imports;

use App\Blueprint\Imports\EmployeeImport;
use App\Blueprint\Repositories\EmployeeRepository;
use App\Blueprint\Repositories\UserRepository;
use App\Concrete\BaseImportConcrete;
use App\Enums\CreationType;
use App\Exports\BlankEmployeeTemplateExport;
use App\Http\Requests\EmployeeContact\StoreEmployeeContactRequest;
use App\Models\Employee;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class EmployeeImportConcrete extends BaseImportConcrete implements EmployeeImport
{
    public function exportTemplate(): string
    {
        return BlankEmployeeTemplateExport::class;
    }

    public function validateData($data, $companyId): array
    {
        $dataToImport = [];
        $existingNumbers = $this->getExistingEmployeeNumbers($companyId);
        $fileNumbers = [];
        $fileOfficeEmails = [];

        foreach ($data as $index => $row) {

            $validationErrors = [];

            if (empty($row['number'])) {
                $validationErrors[] = 'Number is required.';
            } else {
                if (in_array($row['number'], $existingNumbers)) {
                    $validationErrors[] = 'Number already exists in the system.';
                }

                if (in_array($row['number'], $fileNumbers)) {
                    $validationErrors[] = 'Duplicate employee number.';
                } else {
                    $fileNumbers[] = $row['number'];
                }
            }

            if (empty($row['family_name'])) {
                $validationErrors[] = 'Family name is required.';
            }

            if (empty($row['given_name'])) {
                $validationErrors[] = 'Given name is required.';
            }

            if (!empty($row['office_email'])) {

                $officeEmailValidation = Validator::make($row,[
                    'office_email' => [
                        'email:rfc',
                        ...(App::environment('production') ? [
                            Rule::unique('users', 'email')
                        ] : [])
                    ],
                ]);

                if(App::environment('production') && $this->isEmailTaken($row['office_email'])) {
                    $validationErrors[] = 'Email already taken.';
                }

                if ($officeEmailValidation->fails()) {
                    $validationErrors[] = $officeEmailValidation->errors()->first();
                } else {
                    if(App::environment('production')){

                        if (in_array($row['office_email'], $fileOfficeEmails)) {
                            $validationErrors[] = 'Duplicate office email.';
                        } else {
                            $fileOfficeEmails[] = $row['office_email'];
                        }
                    }
                }
            }

            $row['validation_errors'] = $validationErrors;

            $dataToImport[] = $row;
        }

        return $dataToImport;
    }

    public function getExistingEmployeeNumbers($companyId): array
    {
        return Employee::where('company_id', $companyId)
            ->pluck('number')
            ->toArray();
    }

    public function isEmailTaken(string $email): bool
    {
        return new StoreEmployeeContactRequest()->isEmailTaken($email);
    }

    public function resolvedData($data, $companyId): array
    {
        foreach ($data as $index => $row) {

            $autogeneratedUser = null;

            if (!empty($row['office_email'])) {

                $autogeneratedUser = App::make(UserRepository::class)->autoGenerate([
                    'company_id' => $companyId,
                    'office_email' => $row['office_email'],
                    'family_name' => $row['family_name'],
                    'given_name' => $row['given_name'],
                ]);
            }

            $createEmployee = [
                ...(!empty($autogeneratedUser) ? [
                    'user_id' => $autogeneratedUser->id,
                ] : []),
                'company_id' => $companyId,
                'number' => $row['number'],
                'family_name' => $row['family_name'],
                'given_name' => $row['given_name'],
                'creation_type' => CreationType::IMPORT,
            ];

            $employee = App::make(EmployeeRepository::class)->model()::create($createEmployee);
            $employee->contact()->create([
                'office_email' => $row['office_email']
            ]);
        }

        return array_map(function ($row) {return $row['id'];}, $data);
    }
}
