<?php

namespace App\Providers;

use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider implements DeferrableProvider
{
    public $bindings = [

    ];

    public function provides()
    {
        return parent::provides(); // TODO: Change the autogenerated stub
    }
}
